pipeline {
  agent { label 'docker' }
    stages {
      stage('Docker build') {
        steps {
          script {
            dockerImage = docker.build("riscosdotinfo/ubuntu-gccsdk-env:focal", ".")
	    docker.withRegistry('https://registry.hub.docker.com', 'dockerHub') {
              dockerImage.push()
            }
          }
	}
      }
    }

}
